#
# Copyright (c) Contributors to the Open 3D Engine Project.
# For complete copyright and license terms please see the LICENSE at the root of this distribution.
#
# SPDX-License-Identifier: Apache-2.0 OR MIT
#
#

# This workflow is designed to run from a separate repository with cross-repo access.
# It monitors the AR workflow in o3de/o3de and retries failed jobs.

name: AR Retry Failed Jobs

on:
  # Trigger via webhook from the source repo (recommended)
  repository_dispatch:
    types: [ar-workflow-completed]
  # Or run on a schedule to poll for failed workflows
  schedule:
    - cron: '*/15 * * * *'  # Every 15 minutes
  # Manual trigger
  workflow_dispatch:
    inputs:
      run_id:
        description: 'Specific workflow run ID to retry (optional)'
        required: false
        type: string

env:
  MAX_RETRY_ATTEMPTS: 3
  MAX_AGE_HOURS: 24
  TARGET_REPO: amzn-changml/o3de
  TARGET_WORKFLOW: ar.yml

jobs:
  retry-ar-failed-jobs:
    name: Retry AR Failed Jobs
    runs-on: ubuntu-latest
    steps:
      - name: Get failed workflow run
        id: get-run
        env:
          GH_TOKEN: ${{ secrets.O3DE_WORKFLOW_TOKEN }}
        run: |
          # If run_id is provided via workflow_dispatch, use it
          if [ -n "${{ inputs.run_id }}" ]; then
            RUN_ID="${{ inputs.run_id }}"
          # If triggered via repository_dispatch, get run_id from payload
          elif [ "${{ github.event_name }}" == "repository_dispatch" ]; then
            RUN_ID="${{ github.event.client_payload.run_id }}"
          # Otherwise, find the most recent failed AR workflow run
          else
            RUN_ID=$(gh run list \
              --repo ${{ env.TARGET_REPO }} \
              --workflow ${{ env.TARGET_WORKFLOW }} \
              --status failure \
              --limit 1 \
              --json databaseId \
              --jq '.[0].databaseId // empty')
          fi

          if [ -z "$RUN_ID" ]; then
            echo "No failed workflow runs found."
            echo "found=false" >> $GITHUB_OUTPUT
            exit 0
          fi

          # Get run details
          RUN_INFO=$(gh run view $RUN_ID --repo ${{ env.TARGET_REPO }} --json attempt,createdAt)
          ATTEMPT=$(echo "$RUN_INFO" | jq -r '.attempt')
          CREATED_AT=$(echo "$RUN_INFO" | jq -r '.createdAt')

          # Check if run is within the time limit
          CREATED_EPOCH=$(date -d "$CREATED_AT" +%s)
          NOW_EPOCH=$(date +%s)
          AGE_HOURS=$(( (NOW_EPOCH - CREATED_EPOCH) / 3600 ))

          if [ $AGE_HOURS -ge ${{ env.MAX_AGE_HOURS }} ]; then
            echo "Workflow run is $AGE_HOURS hours old, exceeds ${{ env.MAX_AGE_HOURS }} hour limit."
            echo "found=false" >> $GITHUB_OUTPUT
            exit 0
          fi

          echo "run_id=$RUN_ID" >> $GITHUB_OUTPUT
          echo "found=true" >> $GITHUB_OUTPUT
          echo "attempt=$ATTEMPT" >> $GITHUB_OUTPUT
          echo "age_hours=$AGE_HOURS" >> $GITHUB_OUTPUT

      - name: Retry failed jobs
        if: ${{ steps.get-run.outputs.found == 'true' && steps.get-run.outputs.attempt < env.MAX_RETRY_ATTEMPTS }}
        env:
          GH_TOKEN: ${{ secrets.O3DE_WORKFLOW_TOKEN }}
        run: |
          gh run rerun ${{ steps.get-run.outputs.run_id }} --failed -R ${{ env.TARGET_REPO }}

      - name: Notify retry limit reached
        if: ${{ steps.get-run.outputs.found == 'true' && steps.get-run.outputs.attempt >= env.MAX_RETRY_ATTEMPTS }}
        run: |
          echo "::warning::Maximum retry attempts (${{ env.MAX_RETRY_ATTEMPTS }}) reached for workflow run ${{ steps.get-run.outputs.run_id }}. Manual intervention may be required."
